NAMESERVER = server
NAMECLIENT = client
NAMESERVERBONUS = server_bonus
NAMECLIENTBONUS = client_bonus
NAME = utilits.c
SRCSERVER = server.c
SRCCLIENT = client.c
SRCSERVERBONUS = server_bonus.c
SRCCLIENTBONUS = client_bonus.c
FLAGS = -Wall -Wextra -Werror
CC = gcc
OBJSERVER = $(SRCSERVER:.c=.o)
OBJCLIENT = $(SRCCLIENT:.c=.o)
OBJSERVERBONUS = $(SRCSERVERBONUS:.c=.o)
OBJCLIENTBONUS = $(SRCCLIENTBONUS:.c=.o)
OBJNAME = $(NAME:.c=.o)

all:  $(NAMESERVER) $(NAMECLIENT) $(NAMESERVERBONUS) $(NAMECLIENTBONUS)

$(NAME) : all

$(NAMESERVER) : $(OBJSERVER)
	$(CC) $(OBJSERVER) -o $(NAMESERVER) $(NAME)

$(NAMECLIENT) : $(OBJCLIENT)
	$(CC) $(OBJCLIENT) -o $(NAMECLIENT) $(NAME)

$(NAMESERVERBONUS) : $(OBJSERVERBONUS)
	$(CC) $(OBJSERVERBONUS) -o $(NAMESERVERBONUS) $(NAME)

$(NAMECLIENTBONUS) : $(OBJCLIENTBONUS)
	$(CC) $(OBJCLIENTBONUS) -o $(NAMECLIENTBONUS) $(NAME)

clean:
	rm -rf $(OBJSERVER) $(OBJCLIENT) $(OBJSERVERBONUS) $(OBJCLIENTBONUS)

fclean: clean
	rm -rf $(NAMESERVER) $(NAMECLIENT) $(NAMESERVERBONUS) $(NAMECLIENTBONUS)

norm:
	norminette *.[ch]

re:
	fclean all

.PHONY : re fclean clean all  norm
